services:
  TurboLabIt\ChromeHeadless\ChromeHeadless:
    arguments:
      $arrConfig:
        browser:
          windowSize:
              - 1920
              - 1080
          ignoreCertificateErrors: true
          userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36'
        cache:
          ttl: 3600
        pdf:
          outDirFullPath: '%kernel.project_dir%/var/pdf/'
          autoext: true
          browser:
            printBackground: true
            marginTop: 0
            marginBottom: 0
            marginLeft: 0
            marginRight: 0
